// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSession(arg1) {
  return window['go']['app']['App']['CloseSession'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['app']['App']['DeleteConnection'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['app']['App']['DeleteGroup'](arg1);
}

export function GetActiveSessions() {
  return window['go']['app']['App']['GetActiveSessions']();
}

export function GetConnection(arg1) {
  return window['go']['app']['App']['GetConnection'](arg1);
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function ListConnections() {
  return window['go']['app']['App']['ListConnections']();
}

export function ListGroups() {
  return window['go']['app']['App']['ListGroups']();
}

export function ResizeSession(arg1, arg2, arg3) {
  return window['go']['app']['App']['ResizeSession'](arg1, arg2, arg3);
}

export function SaveConnection(arg1) {
  return window['go']['app']['App']['SaveConnection'](arg1);
}

export function SaveGroup(arg1) {
  return window['go']['app']['App']['SaveGroup'](arg1);
}

export function SaveSetting(arg1, arg2) {
  return window['go']['app']['App']['SaveSetting'](arg1, arg2);
}

export function StartSession(arg1) {
  return window['go']['app']['App']['StartSession'](arg1);
}

export function SubmitMFAResponse(arg1, arg2) {
  return window['go']['app']['App']['SubmitMFAResponse'](arg1, arg2);
}

export function TestConnection(arg1) {
  return window['go']['app']['App']['TestConnection'](arg1);
}

export function WriteToSession(arg1, arg2) {
  return window['go']['app']['App']['WriteToSession'](arg1, arg2);
}
