// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function CloseSession(arg1:string):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteGroup(arg1:string):Promise<void>;

export function GetActiveSessions():Promise<Array<domain.ActiveSession>>;

export function GetConnection(arg1:string):Promise<domain.Connection>;

export function GetSettings():Promise<domain.AppSettings>;

export function ListConnections():Promise<Array<domain.Connection>>;

export function ListGroups():Promise<Array<domain.Group>>;

export function ResizeSession(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveConnection(arg1:domain.Connection):Promise<void>;

export function SaveGroup(arg1:domain.Group):Promise<void>;

export function SaveSetting(arg1:string,arg2:string):Promise<void>;

export function StartSession(arg1:string):Promise<string>;

export function SubmitMFAResponse(arg1:string,arg2:Array<string>):Promise<void>;

export function TestConnection(arg1:string):Promise<void>;

export function WriteToSession(arg1:string,arg2:string):Promise<void>;
